### ISSUE TITLE
Get-FirmwareApplicablePayload needs "Update Job Name" parameter

### ISSUE THREAD

**Issue by thomsonac** [dell/OpenManage-PowerShell-Modules#1]
Looking great Trevor!  While starting to code out our automated updates, it looks like the Firmware Update jobs all have a hard-coded name of "Update Firmware-Test" in the function Get-FirmwareApplicablePayload.  I'd suggest adding either a mandatory parameter as part of Update-OMEFirmware (preferred) or do a simple calculation of how many devices are being updated and set the job name to something like "Update Firmware-23 Devices"

**Comment by TrevorSquillario** [comment]
Fixed! You can just do a git pull and run the Install-Module.ps1 again. This will update the Module. Release to the PowerShell Gallery is in the works. It requires a Code Signing Certificate that I need to work out some details on.
