### ISSUE TITLE
New-OMEDiscovery - The property 'RunLater' cannot be found on this object.

### ISSUE THREAD

**Issue by ui-nate-baker** [dell/OpenManage-PowerShell-Modules#11]
I am trying to create a new discovery job using the PS module for OME.  I would like to run at later date.  To do this, I am using the following:
`New-OMEDiscovery -Name "Discovery-$parentGroupName" -DeviceType "Server" -Hosts $group2uRackServers.ip `
        -DiscoveryUserName $input1.UserName -DiscoveryPassword $input1.Password -SetTrapDestination -SetCommunityString 
        -Schedule "runlater" -ScheduleCron "0 0 0 ? * sun *" `

When I run that command I get the following error.  If I remove the schedule and cron switches the commands creates the job and immediately runs. 

> ERROR: Exception setting "RunLater": "The property 'RunLater' cannot be found on this object. Verify that the property exists and can be set."
> 
> 
> PSMessageDetails      :
> Exception             : System.Management.Automation.SetValueInvocationException: Exception setting "RunLater": "The property 'RunLater' cannot be found on this object. Verify that     
>                         the property exists and can be set." ---> System.Management.Automation.RuntimeException: The property 'RunLater' cannot be found on this object. Verify that     
>                         the property exists and can be set.
>                            at System.Management.Automation.Language.PSSetMemberBinder.SetAdaptedValue(Object obj, String member, Object value)
>                            --- End of inner exception stack trace ---
>                            at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>                            at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>                            at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>                            at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> TargetObject          :
> CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
> FullyQualifiedErrorId : ExceptionWhenSetting
> ErrorDetails          :
> InvocationInfo        : System.Management.Automation.InvocationInfo
> ScriptStackTrace      : at Get-DiscoverDevicePayload, C:\Users\nathbaker-s\Documents\WindowsPowerShell\Modules\DellOpenManage\3.4.1\Public\OME\New-OMEDiscovery.ps1: line 104
>                         at New-OMEDiscovery<Process>, C:\Users\nathbaker-s\Documents\WindowsPowerShell\Modules\DellOpenManage\3.4.1\Public\OME\New-OMEDiscovery.ps1: line 277
>                         at <ScriptBlock>, <No file>: line 1
> PipelineIterationInfo : {}

OME version: 3.10 (Build 169)

**Comment by TrevorSquillario** [comment]
Thanks for reporting this! Fixed in 3.5.1
