### ISSUE TITLE
Feature Request: Multiple -ComponentFilter for Update-OMEFirmware/Get-OMEFirmwareCompliance

### ISSUE THREAD

**Issue by nebb00** [dell/OpenManage-PowerShell-Modules#12]
Is it possible to support passing multiple componetfilters to Update-OMEFirmware and Get-OMEFirmwareCompliance. Maybe like the below?

`$baseline | Get-OMEFirmwareCompliance -DeviceFilter $devices -ComponentFilter ("iDRAC with Lifecycle Controller","OS Drivers Pack") `
`Update-OMEFirmware -Baseline $baseline -DeviceFilter $devices -ComponentFilter ("iDRAC with Lifecycle Controller","OS Drivers Pack") `

I have tried multiple ways, and I do not believe its possible in a single command? I can foreach, but not ideal.

**Comment by TrevorSquillario** [comment]
Yes this is possible! I have it working in my test environment. Give me a chance to test it and I should have a new release out sometime next week.

**Comment by nebb00** [comment]
> Yes this is possible! I have it working in my test environment. Give me a chance to test it and I should have a new release out sometime next week.

Look at that service! Also would be cool to accept an array with the values

**Comment by TrevorSquillario** [comment]
Added to Release 3.6.2
https://github.com/dell/OpenManage-PowerShell-Modules/releases/tag/3.6.2

**Comment by TrevorSquillario** [comment]
Example:

```
Update-OMEFirmware -Baseline $("AllLatest" | Get-OMEFirmwareBaseline) -ComponentFilter "BIOS", "iDRAC" -UpdateSchedule "StageForNextReboot" -ClearJobQueue
```
