### ISSUE TITLE
Feature Request - MX7000 Ideas

### ISSUE THREAD

**Issue by nebb00** [dell/OpenManage-PowerShell-Modules#13]
Got some ideas if you're interesting in improving the functionality for the MX chassis'. I have a barbaric powershell script i did a few years ago, can share if interested in some of the leg work. But some high level;

1. Create/Modify/Delete Network "VLANs"
      - Would need to grab the network "QOS" types - GET "/api/NetworkConfigurationService/NetworkTypes"
      - Network Name and Description
      - VLAN Start/Min and VLAN End/Max (aka the range, both the same value for singular)
      - Create network with - POST "/api/NetworkConfigurationService/Networks"
      - Delete network with - DELETE "/api/NetworkConfigurationService/Networks(Id)"

2. Add/Remove Network from template, including "PropagateVlan" 
     - Get Template Details  "/api/TemplateService/Templates($($template.Id))/Views(4)/AttributeViewDetails"
     - Add Network - "/api/TemplateService/Actions/TemplateService.UpdateNetworkConfig"

**Comment by TrevorSquillario** [comment]
Always open to improvements and feedback is welcome! 

1. `New-OMENetwork` `Remove-OMENetwork` exist already but could use some improvements around the Type field. It's just an integer now. Would need to add `Get-OMENetworkTypes` commandlet to return the Network Types. `Edit-OMENetwork` would need to be added.
2. `Set-OMETemplateNetwork` will do that for you :)

Here is an example MX bare metal deployment script using the provided commandlets.
https://github.com/dell/OpenManage-PowerShell-Modules/blob/main/Examples/Chassis-BareMetalProvision.ps1

**Comment by nebb00** [comment]
Not sure how I missed those commands. I will give them a go. Thank you. `Get-OMENetworkTypes` and `Edit-OMENetwork` would be pretty helpful
