### ISSUE TITLE
Set-OMETemplateNetwork not working

### ISSUE THREAD

**Issue by nebb00** [dell/OpenManage-PowerShell-Modules#14]
@TrevorSquillario - First sorry for the influx of issues, I have created. Its also totally possible I am doing something stupid...

`"TEST_VLAN_11" | Get-OMENetwork `
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/bb80468d-2e38-4a1e-bec1-91887e0893c6)

`"TEST_TEMPLATE" | Get-OMETemplate`
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/f45ffdf5-05fa-4bbb-81bf-3c22a5d54632)

`"TEST_TEMPLATE" | Get-OMETemplate | Get-OMETemplateNetwork `
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/16ccf921-ef07-4f4f-bba9-b89c419a6226)

`"TEST_TEMPLATE" | Get-OMETemplate | Set-OMETemplateNetwork -NICIdentifier "NIC in Mezzanine 1A" -Port 1 -TaggedNetworks $("TEST_VLAN_11" | Get-OMENetwork) -Verbose`
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/d51264a6-d2ae-4d65-bb5f-7a17b93adb10)

`"TEST_TEMPLATE" | Get-OMETemplate | Get-OMETemplateNetwork `
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/c4fa5859-e94b-41d5-b15b-6dd1cddb0aed)

***if I then manually add "TEST_VLAN_11" to "Port 1" in the GUI***
`"TEST_TEMPLATE" | Get-OMETemplate | Get-OMETemplateNetwork `
![image](https://github.com/dell/OpenManage-PowerShell-Modules/assets/43903113/83151301-33a1-4b8e-a87c-7f693de22f24)

**Comment by TrevorSquillario** [comment]
Just add the `-Mode "Append"` parameter. It was supposed to throw an error if you don't specify it, that wasn't working. I added a fix for it in future releases.

**Comment by nebb00** [comment]
> Just add the `-Mode "Append"` parameter. It was supposed to throw an error if you don't specify it, that wasn't working. I added a fix for it in future releases.

Thank you. Is it possible to pass two ports in the same command?

**Comment by TrevorSquillario** [comment]
Technically yes but I'm going to leave it as separate commands for now. Could be a potential enhancement in the future.
