### ISSUE TITLE
New-OMEDiscovery / Edit-OMEDiscovery Windows Servers Discovery (SSH)

### ISSUE THREAD

**Issue by FrancoisSSC** [dell/OpenManage-PowerShell-Modules#19]
Hi,

Is it possible to add an argument (e.g., -DiscoveryProtocol SSH) to the New-OMEDiscovery and Edit-OMEDiscovery commands, in order to specify that the protocol/credentials are for Windows Servers? As I understand it, the current commands only allow adding iDRAC.

`"DISCOVERY-WINDOWS" | Get-OMEDiscovery | Edit-OMEDiscovery -Hosts @('SERVERNAME.domain.local) -Mode "Append" -DiscoveryUserName "Domain\Administrator" -DiscoveryPassword $(ConvertTo-SecureString 'Password' -AsPlainText -Force) -DiscoveryProtocol SSH`

![SSH](https://github.com/dell/OpenManage-PowerShell-Modules/assets/160962467/9ffa9508-e344-4f6d-a3c8-6c768c0ebc05)

Thank you!

**Comment by TrevorSquillario** [comment]
Added to Release 3.8.0

https://github.com/dell/OpenManage-PowerShell-Modules/releases/tag/3.8.0

**Comment by TrevorSquillario** [comment]
Add the `-Protocol "SSH"` parameter to `New-OMEDiscovery` or `Edit-OMEDiscovery`. I didn't add support for `sudo` at this point, I'm not quite sure how that works on Windows with OME. I know MS added `sudo` recently but OME had it before that. 

I can add that in the future if necessary.
