### ISSUE TITLE
Error if "Set-CertPolicy" already ran (e.g. the .Net class already exists)

### ISSUE THREAD

**Issue by thomsonac** [dell/OpenManage-PowerShell-Modules#2]
We run all of our scripts, where possible, with ErrorActionPreference set to Stop.  If a script utilizing OME is run more than once (e.g. run more than one "Connect-OME") the script will bomb as the PS instance cannot create a duplicate .Net class to ignore self-signed certs.  Changing the following code solves the issue

Connect-OME:
if ($IgnoreCertificateWarning) { Set-CertPolicy }

to

if ($IgnoreCertificateWarning) { try{ Set-CertPolicy } catch{} }

**Comment by TrevorSquillario** [comment]
I'll add this into the next release, thanks!

**Comment by TrevorSquillario** [comment]
Fixed in latest release https://github.com/dell/OpenManage-PowerShell-Modules/releases/tag/2.3.1
