### ISSUE TITLE
OData implementation is not complete

### ISSUE THREAD

**Issue by wgjhstt247** [dell/OpenManage-PowerShell-Modules#25]
Please complete the OData Implementation in the Open Manage API. It currently doesn't support `$select`, `$expand`, and other features, which would make the API calls smaller and faster. I would like to be able to access Devices/InventoryDetails without having to specify a device_id.

**Comment by TrevorSquillario** [comment]
This is a side project of mine and not a fully supported by the OpenManage team. I will relay this FR onto them but I wouldn't set your expectations too high on ever seeing this feature added to the OME API.
