### ISSUE TITLE
Set-OMEPowerState missing Devices module

### ISSUE THREAD

**Issue by workmanm** [dell/OpenManage-PowerShell-Modules#3]
Set-OMEPowerState.ps1 is missing the line below at the beginning.

using module ..\..\Classes\Device.psm1

Without this line the error below is given.

Unable to find type [Device].

**Comment by TrevorSquillario** [comment]
Working on a new release, I'll get this fixed. Thanks!

**Comment by kirzas** [comment]
Hi Trevor,
When do you plan the next release?
DO you have a roadmap, what is going to be in the new release?
It is a pity that the module is not in powershell gallery and that versioning in the manifest is not maintained.

**Comment by TrevorSquillario** [comment]
The plan is to have it in the PowerShell Gallery eventually. Working on that. This is a side project for me and things will happen when they happen. 

I'm currently working on incorporating all the scripts from https://github.com/dell/OpenManage-Enterprise in to the module.

**Comment by TrevorSquillario** [comment]
Fixed in latest release https://github.com/dell/OpenManage-PowerShell-Modules/releases/tag/2.3.1

Added a better CHANELOG and started testing git actions for publishing to PSG.
