### ISSUE TITLE
New-OMEDiscovery - Set Community String for trap destination from Application Settings

### ISSUE THREAD

**Issue by SirRuggie** [dell/OpenManage-PowerShell-Modules#6]
Good Afternoon, 

I'm trying to check the Additional Options check box when discovering a new device. 
I've not been able to determine how to do this and the Engineers at Dell say they're unfamiliar with the API.

The -SetTrapDestination appears to check the first box to Enable trap reception, but I've been unable to determine how to check the second box which is only available after the first is checked. "Set Community String for trap destination from Application Settings"

![New-OMEDiscoverySNMPTrap](https://user-images.githubusercontent.com/44205022/163233868-5690bc28-9190-43d7-a8d4-79a73f8bacef.png)

**Comment by TrevorSquillario** [comment]
The parameter `-SetCommunityString` will check this for you.

Set Community String for trap destination from Application Settings > Incoming Alerts > SNMP Listener
https://github.com/dell/OpenManage-PowerShell-Modules/blob/main/Documentation/Functions/New-OMEDiscovery.md#-setcommunitystring
