### ISSUE TITLE
Invoke-OMEReport bug

### ISSUE THREAD

**Issue by EugenStelea** [dell/OpenManage-PowerShell-Modules#7]
There is a bug in the Invoke-OMEReport command.
Data is being retrieved, but the headers are mixed up.
See the attached screenshots.
![Invoke-OMEReport_PowerShell](https://user-images.githubusercontent.com/80839623/206188584-daa5e5a4-940c-4eb7-9d3f-8c90791dcce6.png)
![Invoke-OMEReport_OME](https://user-images.githubusercontent.com/80839623/206188587-e2126de0-9a44-45a3-8726-ececf8be36ef.png)

**Comment by TrevorSquillario** [comment]
I had this fixed a while back, just never got around to pushing a release. 3.1.0 should contain the fix!

**Comment by EugenStelea** [comment]
Thank you!
Looking forward for the new release!

**Comment by cah-joe-lumley** [comment]
I'm using 3.2.0 and still experiencing this bug.

**Comment by TrevorSquillario** [comment]
Alright, I'll take a look at this one again

**Comment by cah-joe-lumley** [comment]
> Alright, I'll take a look at this one again

Thanks. It can be re-created by creating a report and then editing the report to change column order.

**Comment by cah-joe-lumley** [comment]
Looks like its still an issue.

I believe this is happening because the FormatOutput-Info function is sorting ColumnNames by Sequence and it should not because the ResultRows are not returned from OME in this order. The ResultRows are returned in the same order as the ColumnNames.

When I remove 'Sort-Object Sequence' it provides results as expected.

**Comment by TrevorSquillario** [comment]
Am I missing something here? It's honoring the Column Order on the Report Definition screen.

![2023-01-20 09_01_48-OpenManage Enterprise](https://user-images.githubusercontent.com/72882537/213746188-4a18140c-f4d7-4141-ba82-4dd15b57b553.png)
![2023-01-20 09_01_22-OpenManage Enterprise](https://user-images.githubusercontent.com/72882537/213746190-b16efdf3-6b71-4362-a235-817dec8a5683.png)

**Comment by TrevorSquillario** [comment]
The fields listed on the Reports page doesn't show the Column Order properly. This is the way OME works it seems.

![2023-01-20 09_04_29-OpenManage Enterprise](https://user-images.githubusercontent.com/72882537/213746609-2535ccf6-2428-4fad-9595-05ed849ae6ae.png)

**Comment by cah-joe-lumley** [comment]
Try adding some columns to your existing report. Such as Hostname, Operating System Name, and OS Version. Then Save and try invoke-omereport.

This is what I see after doing that:

**- Mismatch results from the invoke-omereport**
Device Service Tag                   :   
Device Model                          : Dell HBA355i Fnt
Hostname                                : <removed_device_name>
Operating System Name         : <removed_device_service_tag>
OS Version                               : VxRail E660F
RAID Controller Manufacturer : <removed_hostname>
RAID Controller Name             : VMware ESXi
Device Name                           : 7.0.3 Update 3 Patch 35 (build-19482537) Kernel 7.0.3 (x86_64)

**- Results from ReportResults**
{"@odata.context":"/api/$metadata#ReportService.ReportResult","@odata.type":"#ReportService.ReportResult","@odata.id":"/api/ReportService/ReportDefs(46305)/ReportResults","Id":84,"Title":"perc","TaskId":46300,"ResultRowColumns":[{"Id":869,"Name":"RAID Controller Manufacturer","Width":20.0,"Sequence":5},{"Id":870,"Name":"RAID Controller Name","Width":20.0,"Sequence":6},{"Id":871,"Name":"Device Name","Width":20.0,"Sequence":7},{"Id":872,"Name":"Device Service Tag","Width":20.0,"Sequence":0},{"Id":873,"Name":"Device Model","Width":20.0,"Sequence":1},{"Id":874,"Name":"Hostname","Width":20.0,"Sequence":2},{"Id":875,"Name":"Operating System Name","Width":20.0,"Sequence":3},{"Id":876,"Name":"OS Version","Width":20.0,"Sequence":4}],"ResultRows@odata.navigationLink":"/api/ReportService/ReportDefs(46305)/ReportResults/ResultRows"}

**- Results from ReportResults/ResultsRow**
{"@odata.context":"/api/$metadata#Collection(ReportService.ReportResultRow)","@odata.count":886,"value":[{"@odata.type":"#ReportService.ReportResultRow","Values":["  ","Dell HBA355i Fnt","<removed_device_name>","<removed_device_service_tag>","VxRail E660F","<removed_hostname>","VMware ESXi","7.0.3 Update 3 Patch 35 (build-19482537) Kernel 7.0.3 (x86_64)"]}],"@odata.nextLink":"/api/ReportService/ReportDefs(46305)/ReportResults/ResultRows?$skip=1&$top=1"}

**Comment by TrevorSquillario** [comment]
What version of PowerShell are you using? I am seeing some differences between PS 5 and PS 7.

**Comment by TrevorSquillario** [comment]
Alright, I see what you're saying. Removed `Sort-Object Sequence` and it all matches up.

**Comment by TrevorSquillario** [comment]
Published 3.3.1 that includes this fix. Thanks!
