### ISSUE TITLE
Feature Request - Add command for removing a Firmware Baseline

### ISSUE THREAD

**Issue by EugenStelea** [dell/OpenManage-PowerShell-Modules#9]
Hi,
Can you add a command for removing a Firmware Baseline?
This would be a POST method on /UpdateService/Actions/UpdateService.RemoveBaselines
The payload should contain the Baseline ID(s)
Thank you!

**Comment by TrevorSquillario** [comment]
I'll get this commandlet added in the next release

**Comment by EugenStelea** [comment]
Cool!
Thank you!
